(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/address/addlist"],{2015:function(t,n,e){"use strict";(function(t){Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var o=a(e("2cf7"));function a(t){return t&&t.__esModule?t:{default:t}}var i={name:"",components:{},props:{locdata:{type:Array},text:{type:String},hasMore:{type:Boolean},isLoding:{type:Boolean}},data:function(){return{idx:0,flag:!1,message:!0,msg:""}},methods:{Select:function(n,e){this.idx=e,t.navigateTo({url:"/pages/communityForum/introduction/introduction?id=".concat(n.village_id)})},look:function(n){t.navigateTo({url:"/pages/address/addediting/ADDediting?id=".concat(n.id)})},order:function(n){var e=this;t.showLoading({title:"预约中..."}),o.default.bookingElevator({data:{id:n.id,toFloor:1},fail:function(n){t.hideLoading(),t.showToast({title:"网络错误",icon:"none"})},success:function(n){t.hideLoading(),200==n.statusCode&&(200==n.data.code?(e.message=!0,e.msg=n.data.msg):(e.msg=n.data.msg,e.message=!1))}}),this.flag=!0},sure:function(){this.flag=!1}},mounted:function(){},onShow:function(){},onLoad:function(){},filters:{},computed:{},watch:{},directives:{}};n.default=i}).call(this,e("543d")["default"])},"2fd7":function(t,n,e){"use strict";var o;e.d(n,"b",(function(){return a})),e.d(n,"c",(function(){return i})),e.d(n,"a",(function(){return o}));var a=function(){var t=this,n=t.$createElement;t._self._c},i=[]},b30e:function(t,n,e){},b4f6:function(t,n,e){"use strict";e.r(n);var o=e("2015"),a=e.n(o);for(var i in o)"default"!==i&&function(t){e.d(n,t,(function(){return o[t]}))}(i);n["default"]=a.a},c3b9:function(t,n,e){"use strict";e.r(n);var o=e("2fd7"),a=e("b4f6");for(var i in a)"default"!==i&&function(t){e.d(n,t,(function(){return a[t]}))}(i);e("de39");var d,u=e("f0c5"),c=Object(u["a"])(a["default"],o["b"],o["c"],!1,null,"58cdb68e",null,!1,o["a"],d);n["default"]=c.exports},de39:function(t,n,e){"use strict";var o=e("b30e"),a=e.n(o);a.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/address/addlist-create-component',
    {
        'components/address/addlist-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("c3b9"))
        })
    },
    [['components/address/addlist-create-component']]
]);
